_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
                - 105
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.8
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
architecture:
    value: gpt-moe
array_size:
    value: 20
dataset:
    value: sorting_array
epochs:
    value: 10
learning_rate:
    value: 0.02
max_value:
    value: 20
min_value:
    value: 0
